// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPI_Equipamentos.Contexto;

#nullable disable

namespace WebAPI_Equipamentos.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_Equipamentos.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Equipment_model_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");
                    b.HasKey("Equipment_model_id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("WebAPI_Equipamentos.Models.Equipment_model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Equipment_model");
                });

            modelBuilder.Entity("WebAPI_Equipamentos.Models.Equipment_model_state_hourly_earnings", b =>
                {
                    b.Property<Guid>("Equipment_model_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Equipment_state_id")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Equipment_model_id");
                    b.HasKey("Equipment_state_id");

                    b.ToTable("Equipment_model_state_hourly_earnings");
                });

            modelBuilder.Entity("WebAPI_Equipamentos.Models.Equipment_position_history", b =>
                {
                    b.Property<Guid>("Equipment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.HasKey("Equipment_id");

                    b.ToTable("Equipment_position_history");
                });

            modelBuilder.Entity("WebAPI_Equipamentos.Models.Equipment_state", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Equipment_state");
                });

            modelBuilder.Entity("WebAPI_Equipamentos.Models.Equipment_state_history", b =>
                {
                    b.Property<Guid>("Equipment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Equipment_state_id")
                        .HasColumnType("uuid");

                    b.HasKey("Equipment_id");
                    b.HasKey("Equipment_state_id");

                    b.ToTable("Equipment_state_history");
                });
#pragma warning restore 612, 618
        }
    }
}
